stages:
    - build
    - test

build-code:
    stage: build
    services: 
        - comp1055_2024_coursework_service
    tags:
        - comp1055_2024_coursework_part_01_sandbox
    artifacts:
        name: "$CI_COMMIT_REF_NAME"
        when: on_success
        expire_in: 1 hour
        paths:
            - log/
    script:
        - run_build

test-code:
    stage: test
    tags:
        - comp1055_2024_coursework_part_01_assessor
    artifacts:
        name: "$CI_COMMIT_REF_NAME"
        when: on_success
        expire_in: 1 week
        paths:
            - log/
    script:
        - run_test
